### ISSUE TITLE
istanbul-coveralls is not recognized as a command or executable

### ISSUE THREAD

**Issue by ETHproductions** [shinnn/istanbul-coveralls#1]
I'm running Node 4.4.7 on Windows 7, and after executing `npm install istanbul-coveralls --save-dev` and entering the command `istanbul-coveralls`, I get the "istanbul-coveralls is not recognized" error. `istanbul` is already installed and works properly. Anything I might be doing wrong?

Also, would `node node_modules/istanbul-coveralls/index.js` do the same thing?

**Comment by shinnn** [comment]
Don't use obsolete Windows 7. Just upgrade to Windows 10.
