### ISSUE TITLE
Add an option to configure coverage directory path

### ISSUE THREAD

**Issue by rbecheras** [shinnn/istanbul-coveralls#2]
Example: 

```
$  yarn test && istanbul-coveralls -d ./build/coverage
```

or even simpler:

```
$  yarn test && istanbul-coveralls ./build/coverage
```

Using `./coverage` as default value.

Else, if the coverage file is not in the `./coverage`, the command, course, fails like in this failing travis job:

==>  https://travis-ci.org/sirap-group/swap-browser-lib-boilerplate/jobs/336480376

**Comment by shinnn** [comment]
Thanks for the suggestion, but I'd like to keep this tool as simple as possible.
